apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docker-registry

resources:
- namespace.yaml
- docker-registry.yaml

# # Source: docker-registry/templates/secret.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: docker-registry-secret
#   labels:
#     app: docker-registry
#     chart: docker-registry-1.9.4
#     heritage: Helm
#     release: docker-registry
# type: Opaque
# data:
#   htpasswd: X19QTEFDRUhPTERFUl9GT1JfSFRQQVNTV0RfUEFUQ0hfXw==
#   haSharedSecret: "X19QTEFDRUhPTERFUl9GT1JfU0hBUkVEX1NFQ1JFVF9QQVRDSF9f"

secretGenerator:
- name: docker-registry-secret
  type: Opaque
  namespace: docker-registry
  files:
    - htpasswd=secret/docker-registry.htpasswd
    - haSharedSecret=secret/docker-registry.haSharedSecret

generatorOptions:
  disableNameSuffixHash: true