ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts:
    # Drone does not work with paths, so we use a domain here:
    # https://github.com/drone/drone/issues/475
    - host: ___PLACEHOLDER_DRONE_DOMAIN___
      paths:
        - "/"
  tls:
   - secretName: ___PLACEHOLDER_DRONE_TLS_SECRET_NAME___
     hosts:
       - ___PLACEHOLDER_DRONE_DOMAIN___

persistentVolume:
  ## If you are using SQLite as your DB for Drone, it is recommended to enable persistence. If
  ## enabled, the Chart will create a PersistentVolumeClaim to store its state in. If you are
  ## using a DB other than SQLite, set this to false to avoid allocating unused storage.
  ## If set to false, Drone will use an emptyDir instead, which is ephemeral.
  ##
  enabled: false

extraSecretNamesForEnvFrom:
  # Sets:
  # - DRONE_RPC_SECRET
  - drone-rpc
  # Sets:
  # - DRONE_GITHUB_CLIENT_ID
  # - DRONE_GITHUB_CLIENT_SECRET
  - drone-github-client

env:
  ## REQUIRED: Set the user-visible Drone hostname, sans protocol.
  ## Ref: https://docs.drone.io/installation/reference/drone-server-host/
  ##
  DRONE_SERVER_HOST: ___PLACEHOLDER_DRONE_DOMAIN___
  ## The protocol to pair with the value in DRONE_SERVER_HOST (http or https).
  ## Ref: https://docs.drone.io/installation/reference/drone-server-proto/
  ##
  DRONE_SERVER_PROTO: https
