apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone

resources:
- namespace.yaml
- drone.yaml
- drone-runner-kube.yaml

secretGenerator:
- name: drone-github-client
  type: Opaque
  namespace: drone
  env: "secret/drone-github-client"
- name: drone-rpc
  type: Opaque
  namespace: drone
  env: secret/drone-rpc

generatorOptions:
  disableNameSuffixHash: true