apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: argocd

resources:
- namespace.yaml

bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.6.2
# Use this one for a HA deployment
# - github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v1.6.2