#!/usr/bin/env bash
set -euo pipefail

LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL}"
DOCKER_REGISTRY_DOMAIN="${DOCKER_REGISTRY_DOMAIN}"
DOCKER_REGISTRY_TLS_SECRET_NAME="${DOCKER_REGISTRY_TLS_SECRET_NAME}"

grep "___PLACEHOLDER_LETSENCRYPT_EMAIL___" -rl k8s | xargs \
    sed -i "s/___PLACEHOLDER_LETSENCRYPT_EMAIL___/${LETSENCRYPT_EMAIL}/g"

grep "___PLACEHOLDER_DOCKER_REGISTRY_DOMAIN___" -rl k8s | xargs \
    sed -i "s/___PLACEHOLDER_DOCKER_REGISTRY_DOMAIN___/${DOCKER_REGISTRY_DOMAIN}/g"

grep "___PLACEHOLDER_DOCKER_REGISTRY_TLS_SECRET_NAME___" -rl k8s | xargs \
    sed -i "s/___PLACEHOLDER_DOCKER_REGISTRY_TLS_SECRET_NAME___/${DOCKER_REGISTRY_TLS_SECRET_NAME}/g"